name: Deploy to EC2

on:
  push:
    branches:
      - main # Adjust to your deployment branch

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH agent and add the private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@51.21.8.249 << 'EOF'
            cd /var/www/html/ticket_booth
            git pull origin main
            npm run dev
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo chown -R www-data:www-data /var/www/html/ticket_booth
            sudo find /var/www/html/ticket_booth -type d -exec chmod 755 {} \;
            sudo find /var/www/html/ticket_booth -type f -exec chmod 644 {} \;
          EOF
